import type { Job, Application, Student, Recruiter, AdminUser, LearningResource, Applicant } from './types'

export const JOBS: Job[] = [
  {
    id: '1',
    title: 'Frontend Engineer',
    company: 'Stripe',
    companyColor: '#635BFF',
    location: 'San Francisco, CA',
    type: 'Full-time',
    salary: '$130,000 – $175,000',
    skills: ['React', 'TypeScript', 'CSS', 'GraphQL', 'Node.js'],
    description: "Stripe is looking for a Frontend Engineer to join our Payments team. You'll build the interfaces used by millions of businesses worldwide to accept payments and grow their revenue. Our frontend team values clean code, accessibility, and performance.",
    responsibilities: [
      'Build and maintain high-quality web applications used by millions of customers',
      'Collaborate with product managers and designers to define and implement new features',
      'Write well-tested, performant, and accessible code',
      'Mentor junior engineers and contribute to code reviews',
      'Participate in on-call rotations and incident response',
    ],
    requirements: [
      "4+ years of experience in frontend engineering",
      "Deep expertise in React and TypeScript",
      "Strong understanding of web performance and accessibility",
      "Experience with REST APIs and GraphQL",
      "BS/MS in Computer Science or equivalent experience",
    ],
    benefits: ['Competitive equity', 'Health, dental & vision', '401(k) matching', 'Unlimited PTO', 'Annual learning stipend of $5,000', 'Remote work flexibility'],
    postedDate: '2026-08-18',
    deadline: '2026-09-30',
    applicants: 214,
    status: 'Open',
    department: 'Engineering',
    experience: '4+ years',
    remote: true,
    recruiterId: 'r1',
  },
  {
    id: '2',
    title: 'Product Designer',
    company: 'Figma',
    companyColor: '#F24E1E',
    location: 'San Francisco, CA',
    type: 'Full-time',
    salary: '$125,000 – $165,000',
    skills: ['Figma', 'Prototyping', 'User Research', 'Design Systems', 'Accessibility'],
    description: "Join Figma's Product Design team and help shape the future of design tooling. You'll work on features that empower millions of designers worldwide, from prototyping to developer handoff.",
    responsibilities: [
      'Design product features from concept through launch',
      'Conduct user research and usability testing',
      'Maintain and evolve the Figma design system',
      'Collaborate closely with engineering and product teams',
      'Communicate design decisions with clear documentation',
    ],
    requirements: [
      '3+ years of product design experience',
      'Expert-level proficiency in Figma',
      'Strong portfolio demonstrating end-to-end design process',
      'Experience with accessibility and inclusive design',
      'Excellent communication and presentation skills',
    ],
    benefits: ['Equity package', 'Full health benefits', 'Remote-friendly', '$2,000 home office stipend', 'Parental leave'],
    postedDate: '2026-08-20',
    deadline: '2026-10-01',
    applicants: 389,
    status: 'Open',
    department: 'Design',
    experience: '3+ years',
    remote: true,
    recruiterId: 'r2',
  },
  {
    id: '3',
    title: 'Data Scientist',
    company: 'Google',
    companyColor: '#4285F4',
    location: 'New York, NY',
    type: 'Full-time',
    salary: '$155,000 – $210,000',
    skills: ['Python', 'SQL', 'TensorFlow', 'BigQuery', 'Statistics'],
    description: "Google's Ads Data Science team is seeking a Data Scientist to analyze large-scale data and drive product strategy. You'll work on machine learning models that impact billions of ad impressions daily.",
    responsibilities: [
      'Build and deploy machine learning models at scale',
      'Analyze complex datasets to uncover actionable insights',
      'Partner with product and engineering teams on data-driven decisions',
      'Develop A/B testing frameworks and interpret results',
      'Communicate findings to leadership and cross-functional partners',
    ],
    requirements: [
      "PhD or Masters in Statistics, CS, or related field",
      '5+ years of industry data science experience',
      'Strong Python and SQL skills',
      'Experience with TensorFlow or PyTorch',
      'Excellent statistical reasoning and communication skills',
    ],
    benefits: ['Industry-leading compensation', 'Google stock', 'Health & wellness programs', 'Free meals', 'On-site gym', 'Global mobility options'],
    postedDate: '2026-08-15',
    deadline: '2026-09-25',
    applicants: 601,
    status: 'Open',
    department: 'Data & Analytics',
    experience: '5+ years',
    remote: false,
    recruiterId: 'r3',
  },
  {
    id: '4',
    title: 'Software Engineering Intern',
    company: 'Microsoft',
    companyColor: '#00A4EF',
    location: 'Redmond, WA',
    type: 'Internship',
    salary: '$52/hr',
    skills: ['C++', 'Python', 'Azure', 'Git', 'Data Structures'],
    description: "Join Microsoft's 12-week summer internship program. You'll work on a meaningful project alongside senior engineers on Azure, Office, or Windows teams, with real impact from day one.",
    responsibilities: [
      'Complete a defined summer project with a measurable outcome',
      'Participate in team stand-ups and sprint planning',
      'Write production-quality code with proper tests',
      'Present your work to leadership at the internship showcase',
      'Collaborate with your mentor and buddy',
    ],
    requirements: [
      'Currently enrolled in a BS/MS/PhD program in CS or related field',
      'Expected graduation between December 2026 and June 2028',
      'Strong programming fundamentals in any language',
      'Familiarity with data structures and algorithms',
      'Strong communication skills',
    ],
    benefits: ['$52/hr compensation', 'Housing stipend', 'Relocation assistance', 'Return offer opportunities', 'Access to all Microsoft campuses'],
    postedDate: '2026-08-25',
    deadline: '2026-10-15',
    applicants: 1847,
    status: 'Open',
    department: 'Engineering',
    experience: 'Internship',
    remote: false,
    recruiterId: 'r4',
  },
  {
    id: '5',
    title: 'Backend Engineer',
    company: 'Shopify',
    companyColor: '#96BF48',
    location: 'Remote',
    type: 'Full-time',
    salary: '$140,000 – $185,000',
    skills: ['Ruby on Rails', 'Go', 'MySQL', 'Redis', 'Kafka'],
    description: "Shopify's Core Platform team is hiring a Backend Engineer to work on the systems that power over 1.7 million merchants. You'll work on high-throughput, distributed systems with massive real-world impact.",
    responsibilities: [
      'Design and build scalable backend services handling millions of daily transactions',
      'Optimize database queries and system performance',
      'Lead technical design reviews and RFC processes',
      'Contribute to our open-source ecosystem',
      'Participate in on-call and incident response',
    ],
    requirements: [
      '5+ years of backend engineering experience',
      'Deep expertise in Ruby, Go, or Java',
      'Experience with distributed systems and databases at scale',
      'Strong understanding of software design patterns',
      'Track record of shipping reliable production systems',
    ],
    benefits: ['Fully remote', 'Stock options', 'Health benefits', '$2,400/yr wellness budget', '$1,000/mo remote stipend', 'Flexible hours'],
    postedDate: '2026-08-10',
    deadline: '2026-09-20',
    applicants: 176,
    status: 'Open',
    department: 'Platform Engineering',
    experience: '5+ years',
    remote: true,
    recruiterId: 'r1',
  },
  {
    id: '6',
    title: 'Machine Learning Engineer',
    company: 'OpenAI',
    companyColor: '#10A37F',
    location: 'San Francisco, CA',
    type: 'Full-time',
    salary: '$180,000 – $250,000',
    skills: ['Python', 'PyTorch', 'CUDA', 'Distributed Training', 'LLMs'],
    description: "OpenAI is looking for Machine Learning Engineers to train and deploy state-of-the-art AI systems. You'll work on the cutting edge of large-scale model training, evaluation, and deployment infrastructure.",
    responsibilities: [
      'Train and fine-tune large language models',
      'Build and maintain distributed training infrastructure',
      'Conduct model evaluations and safety assessments',
      'Collaborate with research teams to productionize experiments',
      'Optimize training efficiency and GPU utilization',
    ],
    requirements: [
      "3+ years of ML engineering experience",
      'Expert knowledge of PyTorch and distributed training',
      'Experience with GPU optimization and CUDA',
      'Strong software engineering fundamentals',
      'PhD or MS in ML, CS, or equivalent preferred',
    ],
    benefits: ['Top-of-market compensation', 'Significant equity', 'Full health & dental', 'Unlimited PTO', '$2,000/mo housing assistance'],
    postedDate: '2026-08-22',
    deadline: '2026-10-05',
    applicants: 523,
    status: 'Open',
    department: 'Research Engineering',
    experience: '3+ years',
    remote: false,
    recruiterId: 'r2',
  },
  {
    id: '7',
    title: 'Product Manager',
    company: 'Airbnb',
    companyColor: '#FF5A5F',
    location: 'San Francisco, CA',
    type: 'Full-time',
    salary: '$155,000 – $200,000',
    skills: ['Product Strategy', 'SQL', 'A/B Testing', 'Roadmapping', 'Stakeholder Management'],
    description: "Airbnb's Host Platform team is seeking a Product Manager to own the end-to-end experience for our 4 million+ hosts. You'll define strategy, drive roadmaps, and collaborate with cross-functional teams to ship products that help hosts succeed.",
    responsibilities: [
      'Define product vision and strategy for the Host Platform',
      'Lead cross-functional teams from discovery through launch',
      'Drive data-informed decisions through experimentation',
      'Manage stakeholder alignment and executive communication',
      'Conduct user research and synthesize insights',
    ],
    requirements: [
      '4+ years of product management experience',
      'Track record of shipping successful consumer products',
      'Strong analytical skills and SQL proficiency',
      'Excellent written and verbal communication',
      'Experience with marketplace or platform products preferred',
    ],
    benefits: ['Competitive salary + equity', 'Annual travel credit', 'Health & wellness', '401(k) match', 'Parental leave', 'Remote flexibility'],
    postedDate: '2026-08-12',
    deadline: '2026-09-22',
    applicants: 448,
    status: 'Open',
    department: 'Product',
    experience: '4+ years',
    remote: true,
    recruiterId: 'r3',
  },
  {
    id: '8',
    title: 'DevOps Engineer',
    company: 'Netflix',
    companyColor: '#E50914',
    location: 'Los Gatos, CA',
    type: 'Full-time',
    salary: '$160,000 – $220,000',
    skills: ['Kubernetes', 'Terraform', 'AWS', 'CI/CD', 'Python'],
    description: "Netflix's Cloud Platform team builds the infrastructure that streams to 260 million subscribers. As a DevOps Engineer, you'll work on deployment pipelines, reliability engineering, and the systems that keep Netflix running at massive scale.",
    responsibilities: [
      'Design and maintain Kubernetes clusters and CI/CD pipelines',
      'Drive infrastructure automation with Terraform',
      'Improve system reliability and on-call tooling',
      'Collaborate with service teams on cloud architecture',
      'Lead incident response and post-mortems',
    ],
    requirements: [
      '5+ years of DevOps or SRE experience',
      'Expert knowledge of Kubernetes and container orchestration',
      'Strong experience with AWS or GCP',
      'Infrastructure-as-code experience with Terraform',
      'Strong scripting skills in Python or Go',
    ],
    benefits: ['Top-of-industry salary', 'Unlimited PTO', 'Stock options', 'Full health coverage', 'Free Netflix', 'On-site fitness'],
    postedDate: '2026-08-08',
    deadline: '2026-09-18',
    applicants: 298,
    status: 'Open',
    department: 'Infrastructure',
    experience: '5+ years',
    remote: false,
    recruiterId: 'r4',
  },
  {
    id: '9',
    title: 'UX Research Intern',
    company: 'Apple',
    companyColor: '#555555',
    location: 'Cupertino, CA',
    type: 'Internship',
    salary: '$48/hr',
    skills: ['User Research', 'Interviews', 'Usability Testing', 'Figma', 'Statistics'],
    description: "Join Apple's Human Interface team for a 12-week internship focused on user research for iOS and macOS. You'll conduct research that directly shapes the future of Apple's platforms.",
    responsibilities: [
      'Plan and execute qualitative and quantitative user studies',
      'Conduct moderated usability testing sessions',
      'Synthesize research findings and present to design leadership',
      'Collaborate with designers and engineers on research insights',
      "Contribute to Apple's internal research methods library",
    ],
    requirements: [
      'Currently enrolled in HCI, Psychology, or related graduate program',
      'Experience conducting qualitative user research',
      'Familiarity with usability testing methodologies',
      'Strong communication and presentation skills',
      'Portfolio of research projects required',
    ],
    benefits: ['$48/hr compensation', 'Housing assistance', 'On-site amenities', 'Return offer opportunities', 'Apple product discounts'],
    postedDate: '2026-08-28',
    deadline: '2026-10-20',
    applicants: 1124,
    status: 'Open',
    department: 'Human Interface',
    experience: 'Internship',
    remote: false,
    recruiterId: 'r2',
  },
  {
    id: '10',
    title: 'Security Engineer',
    company: 'Cloudflare',
    companyColor: '#F48120',
    location: 'Austin, TX',
    type: 'Full-time',
    salary: '$145,000 – $190,000',
    skills: ['Network Security', 'Go', 'Rust', 'Cryptography', 'Incident Response'],
    description: "Cloudflare secures and accelerates millions of websites and APIs. As a Security Engineer, you'll work on the systems that protect our global network from sophisticated attacks while serving 50 million HTTP requests per second.",
    responsibilities: [
      'Design and implement network security controls at global scale',
      'Lead security incident response and threat hunting',
      'Conduct security architecture reviews and threat modeling',
      'Develop internal security tooling and automation',
      'Collaborate with product teams on security-by-design',
    ],
    requirements: [
      '4+ years of security engineering experience',
      'Deep understanding of network protocols and cryptography',
      'Experience with Go, Rust, or C++',
      'Track record of incident response at scale',
      'Security certifications (CISSP, OSCP) preferred',
    ],
    benefits: ['Competitive salary + equity', 'Health & dental', 'Remote-friendly', 'Conference budget', '401(k)', 'Home office stipend'],
    postedDate: '2026-08-05',
    deadline: '2026-09-15',
    applicants: 142,
    status: 'Open',
    department: 'Security',
    experience: '4+ years',
    remote: true,
    recruiterId: 'r3',
  },
]

export const MY_APPLICATIONS: Application[] = [
  {
    id: 'a1',
    jobId: '1',
    jobTitle: 'Frontend Engineer',
    company: 'Stripe',
    companyColor: '#635BFF',
    location: 'San Francisco, CA',
    type: 'Full-time',
    salary: '$130,000 – $175,000',
    appliedDate: '2026-08-22',
    status: 'Shortlisted',
    lastUpdated: '2026-08-29',
  },
  {
    id: 'a2',
    jobId: '2',
    jobTitle: 'Product Designer',
    company: 'Figma',
    companyColor: '#F24E1E',
    location: 'San Francisco, CA',
    type: 'Full-time',
    salary: '$125,000 – $165,000',
    appliedDate: '2026-08-24',
    status: 'Under Review',
    lastUpdated: '2026-08-26',
  },
  {
    id: 'a3',
    jobId: '3',
    jobTitle: 'Data Scientist',
    company: 'Google',
    companyColor: '#4285F4',
    location: 'New York, NY',
    type: 'Full-time',
    salary: '$155,000 – $210,000',
    appliedDate: '2026-08-18',
    status: 'Applied',
    lastUpdated: '2026-08-18',
  },
  {
    id: 'a4',
    jobId: '4',
    jobTitle: 'Software Engineering Intern',
    company: 'Microsoft',
    companyColor: '#00A4EF',
    location: 'Redmond, WA',
    type: 'Internship',
    salary: '$52/hr',
    appliedDate: '2026-08-10',
    status: 'Rejected',
    lastUpdated: '2026-08-20',
  },
  {
    id: 'a5',
    jobId: '6',
    jobTitle: 'Machine Learning Engineer',
    company: 'OpenAI',
    companyColor: '#10A37F',
    location: 'San Francisco, CA',
    type: 'Full-time',
    salary: '$180,000 – $250,000',
    appliedDate: '2026-08-15',
    status: 'Selected',
    lastUpdated: '2026-08-28',
  },
  {
    id: 'a6',
    jobId: '5',
    jobTitle: 'Backend Engineer',
    company: 'Shopify',
    companyColor: '#96BF48',
    location: 'Remote',
    type: 'Full-time',
    salary: '$140,000 – $185,000',
    appliedDate: '2026-08-12',
    status: 'Applied',
    lastUpdated: '2026-08-12',
  },
]

export const SAVED_JOBS: Job[] = [JOBS[1], JOBS[2], JOBS[6], JOBS[9]]

export const CURRENT_STUDENT: Student = {
  id: 's1',
  name: 'Alex Chen',
  email: 'alex.chen@stanford.edu',
  role: 'student',
  status: 'Active',
  joined: '2026-01-15',
  university: 'Stanford University',
  major: 'Computer Science, B.S.',
  graduationYear: 'May 2027',
  gpa: '3.87 / 4.00',
  skills: ['React', 'TypeScript', 'Python', 'Node.js', 'SQL', 'Machine Learning', 'Figma', 'Git'],
  bio: "Senior CS student at Stanford with a focus on human-computer interaction and full-stack development. I've built several production web apps and contributed to open-source projects. Looking for full-time roles in product engineering starting June 2027.",
  location: 'Palo Alto, CA',
  phone: '+1 (415) 555-0182',
  linkedin: 'linkedin.com/in/alex-chen-dev',
  github: 'github.com/alexchen',
  portfolio: 'alexchen.dev',
}

export const CURRENT_RECRUITER: Recruiter = {
  id: 'r1',
  name: 'Jordan Lee',
  email: 'jordan.lee@stripe.com',
  role: 'recruiter',
  status: 'Active',
  joined: '2025-03-10',
  company: 'Stripe',
  companyColor: '#635BFF',
  position: 'Senior Technical Recruiter',
  department: 'Talent Acquisition',
  phone: '+1 (415) 555-0241',
  companySize: '5,000–10,000 employees',
  industry: 'Financial Technology',
  website: 'stripe.com/jobs',
}

export const ALL_USERS: AdminUser[] = [
  { id: 's1', name: 'Alex Chen', email: 'alex.chen@stanford.edu', role: 'student', status: 'Active', joined: '2026-01-15', university: 'Stanford University' },
  { id: 's2', name: 'Sarah Johnson', email: 'sarah.j@mit.edu', role: 'student', status: 'Active', joined: '2026-02-08', university: 'MIT' },
  { id: 's3', name: 'Michael Park', email: 'm.park@berkeley.edu', role: 'student', status: 'Active', joined: '2026-01-28', university: 'UC Berkeley' },
  { id: 's4', name: 'Priya Patel', email: 'priya.p@cmu.edu', role: 'student', status: 'Active', joined: '2026-03-04', university: 'Carnegie Mellon' },
  { id: 's5', name: 'James Wilson', email: 'j.wilson@nyu.edu', role: 'student', status: 'Suspended', joined: '2026-02-20', university: 'New York University' },
  { id: 's6', name: 'Emma Davis', email: 'e.davis@columbia.edu', role: 'student', status: 'Active', joined: '2026-03-15', university: 'Columbia University' },
  { id: 'r1', name: 'Jordan Lee', email: 'jordan.lee@stripe.com', role: 'recruiter', status: 'Active', joined: '2025-03-10', company: 'Stripe' },
  { id: 'r2', name: 'Morgan Silva', email: 'morgan.s@figma.com', role: 'recruiter', status: 'Active', joined: '2025-06-22', company: 'Figma' },
  { id: 'r3', name: 'Casey Taylor', email: 'casey.t@google.com', role: 'recruiter', status: 'Active', joined: '2025-04-01', company: 'Google' },
  { id: 'r4', name: 'Riley Brown', email: 'riley.b@microsoft.com', role: 'recruiter', status: 'Pending', joined: '2026-08-15', company: 'Microsoft' },
  { id: 'a1', name: 'Sam Torres', email: 'sam.torres@skillbridge.io', role: 'admin', status: 'Active', joined: '2025-01-01' },
]

export const APPLICANTS: Applicant[] = [
  { id: 'ap1', name: 'Sarah Johnson', email: 'sarah.j@mit.edu', university: 'MIT', major: 'Computer Science', gpa: '3.95', skills: ['React', 'TypeScript', 'Node.js', 'Python'], appliedDate: '2026-08-20', jobId: '1', jobTitle: 'Frontend Engineer', status: 'Shortlisted', experience: '2 internships' },
  { id: 'ap2', name: 'Michael Park', email: 'm.park@berkeley.edu', university: 'UC Berkeley', major: 'EECS', gpa: '3.78', skills: ['Vue.js', 'JavaScript', 'CSS', 'PostgreSQL'], appliedDate: '2026-08-21', jobId: '1', jobTitle: 'Frontend Engineer', status: 'Under Review', experience: '1 internship' },
  { id: 'ap3', name: 'Priya Patel', email: 'priya.p@cmu.edu', university: 'Carnegie Mellon', major: 'Software Engineering', gpa: '3.95', skills: ['React', 'TypeScript', 'AWS', 'GraphQL'], appliedDate: '2026-08-19', jobId: '1', jobTitle: 'Frontend Engineer', status: 'Applied', experience: '3 internships' },
  { id: 'ap4', name: 'James Wilson', email: 'j.wilson@nyu.edu', university: 'NYU', major: 'CS + Finance', gpa: '3.62', skills: ['JavaScript', 'React', 'SQL', 'Python'], appliedDate: '2026-08-22', jobId: '1', jobTitle: 'Frontend Engineer', status: 'Rejected', experience: '1 internship' },
  { id: 'ap5', name: 'Emma Davis', email: 'e.davis@columbia.edu', university: 'Columbia', major: 'Computer Science', gpa: '3.88', skills: ['React', 'TypeScript', 'GraphQL', 'Figma'], appliedDate: '2026-08-23', jobId: '1', jobTitle: 'Frontend Engineer', status: 'Applied', experience: '2 internships' },
  { id: 'ap6', name: 'Alex Chen', email: 'alex.chen@stanford.edu', university: 'Stanford', major: 'Computer Science', gpa: '3.87', skills: ['React', 'TypeScript', 'Python', 'Node.js'], appliedDate: '2026-08-22', jobId: '5', jobTitle: 'Backend Engineer', status: 'Selected', experience: '2 internships' },
]

export const LEARNING_RESOURCES: LearningResource[] = [
  { id: 'l1', title: 'Full-Stack Web Development with React & Node.js', provider: 'Coursera', category: 'Web Development', type: 'Course', difficulty: 'Intermediate', duration: '42 hours', rating: 4.8, enrolled: 128400, tags: ['React', 'Node.js', 'MongoDB', 'Express'], featured: true, addedDate: '2026-06-01', image: 'photo-1593642632559-0c6d3fc62b89' },
  { id: 'l2', title: 'Python for Data Science and Machine Learning Bootcamp', provider: 'Udemy', category: 'Data Science', type: 'Course', difficulty: 'Beginner', duration: '25 hours', rating: 4.7, enrolled: 354200, tags: ['Python', 'Pandas', 'Scikit-learn', 'Matplotlib'], featured: true, addedDate: '2026-05-15', image: 'photo-1551288049-bebda4e38f71' },
  { id: 'l3', title: 'System Design Interview — An Insider\'s Guide', provider: 'SkillBridge Learn', category: 'Career Prep', type: 'Workshop', difficulty: 'Advanced', duration: '18 hours', rating: 4.9, enrolled: 62100, tags: ['System Design', 'Architecture', 'Scalability'], featured: true, addedDate: '2026-07-10', image: 'photo-1522071820081-009f0129c71c' },
  { id: 'l4', title: 'AWS Certified Solutions Architect — Associate', provider: 'A Cloud Guru', category: 'Cloud & DevOps', type: 'Certification', difficulty: 'Intermediate', duration: '60 hours', rating: 4.6, enrolled: 89300, tags: ['AWS', 'Cloud', 'Architecture', 'DevOps'], featured: false, addedDate: '2026-04-20', image: 'photo-1451187580459-43490279c0fa' },
  { id: 'l5', title: 'UX Design Foundations: Research, Wireframing & Prototyping', provider: 'Google', category: 'Design', type: 'Course', difficulty: 'Beginner', duration: '32 hours', rating: 4.7, enrolled: 195000, tags: ['UX', 'Figma', 'Research', 'Prototyping'], featured: false, addedDate: '2026-06-18', image: 'photo-1561070791-2526d30994b5' },
  { id: 'l6', title: 'Deep Learning Specialization', provider: 'DeepLearning.AI', category: 'Machine Learning', type: 'Course', difficulty: 'Advanced', duration: '80 hours', rating: 4.9, enrolled: 426000, tags: ['Deep Learning', 'TensorFlow', 'Neural Networks', 'CNN'], featured: true, addedDate: '2026-07-25', image: 'photo-1620712943543-bcc4688e7485' },
  { id: 'l7', title: 'Product Management: From Idea to Launch', provider: 'LinkedIn Learning', category: 'Product Management', type: 'Course', difficulty: 'Beginner', duration: '22 hours', rating: 4.5, enrolled: 74500, tags: ['Product Strategy', 'Roadmapping', 'User Stories', 'Agile'], featured: false, addedDate: '2026-05-30', image: 'photo-1460925895917-afdab827c52f' },
  { id: 'l8', title: 'Technical Interview Mastery', provider: 'SkillBridge Learn', category: 'Career Prep', type: 'Workshop', difficulty: 'Intermediate', duration: '15 hours', rating: 4.8, enrolled: 38200, tags: ['Algorithms', 'LeetCode', 'System Design', 'Behavioral'], featured: false, addedDate: '2026-08-01', image: 'photo-1516321318423-f06f85e504b3' },
]

export const CHART_DATA = {
  applicationTrend: [
    { month: 'Mar', applied: 2, reviews: 1, offers: 0 },
    { month: 'Apr', applied: 4, reviews: 2, offers: 0 },
    { month: 'May', applied: 3, reviews: 3, offers: 1 },
    { month: 'Jun', applied: 6, reviews: 4, offers: 1 },
    { month: 'Jul', applied: 5, reviews: 3, offers: 2 },
    { month: 'Aug', applied: 8, reviews: 5, offers: 2 },
  ],
  recruiterApplications: [
    { name: 'Frontend Eng.', applications: 214, interviews: 18, hires: 2 },
    { name: 'Backend Eng.', applications: 176, interviews: 14, hires: 1 },
    { name: 'Data Scientist', applications: 601, interviews: 22, hires: 3 },
    { name: 'ML Engineer', applications: 523, interviews: 19, hires: 2 },
    { name: 'DevOps Eng.', applications: 298, interviews: 12, hires: 1 },
  ],
  adminGrowth: [
    { month: 'Mar', students: 820, recruiters: 42 },
    { month: 'Apr', students: 1140, recruiters: 58 },
    { month: 'May', students: 1580, recruiters: 74 },
    { month: 'Jun', students: 2210, recruiters: 98 },
    { month: 'Jul', students: 3050, recruiters: 125 },
    { month: 'Aug', students: 4280, recruiters: 168 },
  ],
}
